name: Run SSHX Script on macOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-sshx:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run SSHX Command
        run: curl -sSf https://sshx.io/get | sh -s run
